// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Random
#pragma kernel Blurr
#pragma kernel UpdateAgents

struct Agent {
    float2 position;
    float directionAngle;
    float4 color;
};



// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
RWStructuredBuffer<Agent> Agents;
float time;
float sizeX;
float sizeY;
//between 0 and 1
float feremonIntensity;
float blurrMultiplier;
float randomMult;
float randomRadRange;
float speed;
float radiusOfAgent;
int iterations;

float rand(in float2 uv)
{
    return clamp(frac(sin(dot(uv, float2(12.9898, 78.233) * 2.0)) * 43758.5453), 0.0, 1.0);
}
float randBetween(in float2 uv, in float min, in float max)
{
	return rand(uv) * (max - min) + min;
}
/*
int indexFromId(uint3 id)
{
    return id.x + _CubesPerAxis * (id.y + _CubesPerAxis * id.z);
}
*/
[numthreads(8,8,1)]
void Random (uint3 id : SV_DispatchThreadID)
{        
    float random = rand(float2(id.x * time, id.y * time));
    Result[id.xy] = float4(random, random, random, 1);
}

float4 averageOfNeighbour(float2 uv)
{
    float4 sum = 0;
	for (int i = -1; i <= 1; i++)
	{
		for (int j = -1; j <= 1; j++)
		{
			sum += Result[uv + float2(i, j)];
		}
	}
	return sum / 9;
}

[numthreads(8,8,1)]
void Blurr (uint3 id : SV_DispatchThreadID)
{   
    Result[id.xy] = averageOfNeighbour(id.xy) * blurrMultiplier;//Result[id.xy] * blurrMultiplier; //
}

float4 getColorAtPosition(float2 position)
{
    if(position.x < 0 || position.x > sizeX || position.y < 0 || position.y > sizeY)
	{
        return 0;
    }
    return Result[position];
}

float4 getColorAtLine(float2 position, float directionAngle, float distance)
{
	float2 direction = float2(cos(directionAngle), sin(directionAngle));
    float2 checkPos = position + direction * distance;
    
	float2 currentPosition = position;
	float4 color = 0;
    float iterations = 2;
    float step = distance / iterations;
	for(int i = 0; i < iterations; i++)
	{
        currentPosition += direction * step;
        float4 colorAtPos = getColorAtPosition(currentPosition);
		color += colorAtPos;
        //Result[currentPosition] = float4(0, 1, 0, 0);
	}
	return color;
}

float2 positionFromAngle(float2 start, float distance, float angle)
{
	return start + float2(cos(angle), sin(angle)) * distance;
}

float differenceBetweenColors(float4 color1, float4 color2)
{
	return abs(color1.r - color2.r) + abs(color1.g - color2.g) + abs(color1.b - color2.b);
}

float angleAdditionForFeremonTrails(float2 position, float angle, float4 givenColor)
{
    float checkdistance = 8;
    float startDist = 8;
    //22.5 degrees
    float angleOffset = 3.14159f / 4 /2;
        
    float angles[5] = {0, - angleOffset, + angleOffset, angleOffset *2, angleOffset*-2};
    float4 colorArr[5];
    
    float angleToAdd = 0;
    float currValue = 10000000;
    for(int i = 0; i < 5; i++)
	{
        float currAngle = angle + angles[i];
		colorArr[i] = getColorAtLine(positionFromAngle(position, startDist,currAngle), currAngle, checkdistance);
	    
        float colorDiff = differenceBetweenColors(colorArr[i], givenColor);

        if(colorDiff < currValue)
        {
			angleToAdd = angles[i];
			currValue = colorDiff;
		}
    }
    
    float angleAddition = angleToAdd * feremonIntensity;
    
	return angleAddition;
}

[numthreads(1024,1,1)]
void UpdateAgents (uint3 id : SV_DispatchThreadID)
{   
    for(int i = 0; i < iterations; i++)
    {
    Agent agent = Agents[id.x];
    float angle = agent.directionAngle;
    
    //future position
    float2 directionVec = float2(cos(angle), sin(angle));
    float2 newPos = agent.position + (directionVec*speed);
    
    //collision detection

    
    if (newPos.x < 0 || newPos.x > sizeX)
	{
        angle += 3.14159;
	}
    if (newPos.y < 0 || newPos.y > sizeY)
    {
        angle += 3.14159;
	}

    //follow trails
    float randomValue = randBetween(agent.position * time, -randomRadRange, randomRadRange); 

    if(randBetween(agent.position * time, 0, randomMult) < 1)
    {
        //random variation in movement
        angle += randomValue;
    }
    else{
        angle += randomValue * .1f;
        angle += angleAdditionForFeremonTrails(newPos, angle, agent.color);
    }
    
    //resetting the angle to avoid overflow
    //angle = angle % (2 * 3.14159);
    /*while(angle < 0 )
    {
        angle += 2 * 3.14159;
    }*/
    
    //calculating the vector from the angle
    directionVec = float2(cos(angle), sin(angle));
    //updating the position by the new direction and the speed
    agent.position += (directionVec*speed);
    //updating the angle
    agent.directionAngle = angle;
    //set the agent
	Agents[id.x] = agent;
    //set the pixel

    float2 center = float2(sizeX/2, sizeY/2);
    float distanceToCenter = length(agent.position - center);
    float centerDistPercent = distanceToCenter / (sizeX/2);

    float4 averageColorOfNeighbour = averageOfNeighbour(agent.position);
    //Result[agent.position] = agent.color;
    Result[agent.position] = agent.color;
    }
}