// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel RandomCubes

struct Cube
{
	float3 position;
	float3 color;
};

RWStructuredBuffer<Cube> cubes;
float resolution;

[numthreads(10, 1, 1)]
void RandomCubes (uint3 id : SV_DispatchThreadID)
{
	float xPos = id.x / resolution;
	Cube cube = cubes[id.x];
	cube.color = float4(1, 0.0, 0.0, 1.0);
	
	cubes[id.x] = cube;
}
